### ISSUE TITLE
Use browser "back" button to navigate between searches/queries

### ISSUE THREAD

**Issue by ShaneCourtrille** [datalust/seq-tickets#907] opened 2019-11-20 17:14 UTC
Using back on the browser does not properly load the last query.  The url will update with the correct query but the query itself isn't executed.

**Comment by nblumhardt** [comment] 2019-11-21 05:59
Thanks for the note, @ShaneCourtrille.

This is a duplicate of #614, we'll take a fresh look at it, though 👍

**Closed** 2021-01-21 00:39 UTC
Labels: enhancement
