### ISSUE TITLE
Dashboards: Group signals when adding to charts

### ISSUE THREAD

**Issue by Sebbl22** [datalust/seq-tickets#2129] opened 2024-03-22 07:26 UTC
When adding signals to charts, all signals are ordered alphabetically.
![grafik](https://github.com/datalust/seq-tickets/assets/10319545/41204b3d-d74a-4cfa-9498-a6328328f3ca)

If you have a large amount of signals, it is difficult to find signals, that belong together (e.g. we have signals for Warning, Errors and Fatal, which are displayed at the beginning and end of the list).

I would like to see the signals grouped when adding them to widgets, like in the Events Signals pane.
![grafik](https://github.com/datalust/seq-tickets/assets/10319545/4692df2c-2b39-4e4a-9b93-8d0c68c41611)

![grafik](https://github.com/datalust/seq-tickets/assets/10319545/068ee5e8-f476-4104-8328-9b78bf6b0124)

Thank you

**Comment by nblumhardt** [comment] 2024-03-25 23:45
Thanks for the suggestion, this seems worthwhile, we'll give it some thought :+1:

**Comment by nblumhardt** [comment] 2024-03-26 00:43
This turns out to be a duplicate of #2071

**Closed by nblumhardt** 2024-03-26 00:43 UTC
Labels: enhancement
