### ISSUE TITLE
Seq 4.2 pre auto-refresh clears the screen

### ISSUE THREAD

**Issue by nrandell** [datalust/seq-tickets#643] opened 2017-12-21 08:44 UTC
Slightly strange title, but I've been running the preview for a few days, now on 4.2.305-pre and am seeing a funny behaviour when I turn on auto-refresh.

The first thing that happens is the screen populates fully with the most recent log entries matching the filter, then the screen clears leaving only the most recent messages displayed.

Nothing appears in the javascript console. It happens in Edge and Chrome.

The partial URL is `http://xxxxxx:5341/#/events?signal=signal-517,signal-516&autorefresh`

Once log messages start turning up, the auto refresh works perfectly and the messages populate the screen.

**Comment by nblumhardt** [comment] 2017-12-22 00:25
Hi Nick - thanks for letting us know, we'll take a look 👍 

Best regards,
Nick

**Comment by nblumhardt** [comment] 2018-01-08 03:52
Hi Nick - this one is a little awkwardly "by design" - auto refresh always requests the most recent screenfull of events, discarding whatever result set might already have been retrieved (i.e. through infinite scroll). If the events are scarce, it can take a while to re-request the first screen, so you might notice this more on some result sets than on others.

We've got #605 open to look at this, so I'll close this ticket as essentially a duplicate of that one. Thanks!

**Closed by nblumhardt** 2018-01-08 03:52 UTC
Labels: bug
