### ISSUE TITLE
Value type dashboard widget fades out after dashboard refresh

### ISSUE THREAD

**Issue by CrossBound** [datalust/seq-tickets#1067] opened 2020-11-27 18:29 UTC
**Describe the bug**
Dashboard widgets of type 'Value' seem to get a faded appearance after a refresh of the dashboard occurs.

**To Reproduce**
1. Setup a dashboard widget of type 'Value'
2. Refresh the dashboard

**Expected behavior**
It maintains full color after a refresh.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/11417093/100476623-ae7e8480-30ab-11eb-9545-7068350ac86a.png)

After:
![image](https://user-images.githubusercontent.com/11417093/100476633-b5a59280-30ab-11eb-8104-cf644136b343.png)

**Environment (please complete the following information):**
 - Client OS: Windows 10 Enterprise x64 Version 1809
 - Browser: Firefox Developer 84.0b2 x64
 - Seq Version: 2020.4.5089
 - Using Docker? No

**Additional context**
n/a

**Comment by CrossBound** [comment] 2020-11-27 18:30
I have confirmed this also occurs on MS Edge 86.0.622.69 (Official build) (64-bit)

**Comment by CrossBound** [comment] 2020-11-27 18:32
FYI, this did not occur in 2020.3

**Comment by nblumhardt** [comment] 2020-11-27 20:02
Thanks for the report, @CrossBound ! This is a duplicate of https://github.com/datalust/seq-tickets/issues/1063, which is fixed in 2020.4.5119 (now published).

**Closed by nblumhardt** 2020-11-27 20:02 UTC
Labels: bug

**Comment by CrossBound** [comment] 2020-11-27 20:54
Very good, I'll get it updated.
