### ISSUE TITLE
Unable to see full title of signal

### ISSUE THREAD

**Issue by mjm365** [datalust/seq-tickets#895] opened 2019-10-22 03:44 UTC
If a signal title/name is too long then you can't see the end of the title, see attached screenshot where I have 4 signals that have the same start to their title, meaning I can't tell which is which as the end is cut off.  There is no option to scroll.  Could you please remove the forced width of the title (see attached screenshot), this would then enable the scroll bar should you have long enough titles that need to be views.
![seqissue_resolution](https://user-images.githubusercontent.com/56857714/67257982-d75c3f80-f4d1-11e9-8948-3faaacfbc600.png)
![seqissue](https://user-images.githubusercontent.com/56857714/67257983-d7f4d600-f4d1-11e9-8f68-adf708efa2a9.png)

**Comment by nblumhardt** [comment] 2019-10-22 22:55
Thanks for the note, we'd like to improve this. At the least, we should be able to show the full title on hover in these cases 👍

**Comment by nblumhardt** [comment] 2019-10-27 23:04
Sorry, this is a duplicate of #885, coming in the next preview.

**Closed by nblumhardt** 2019-10-27 23:04 UTC
Labels: enhancement
