### ISSUE TITLE
Allow query syntax keywords to be used as (dotted) property accessors without escaping

### ISSUE THREAD

**Issue by c0shea** [datalust/seq-tickets#2296] opened 2024-10-17 20:18 UTC
**Describe the bug**
I'm trying to select the "From" property on my RequestDto property in the event. I can't use the dot syntax, as Seq reports the error "Syntax error (line 1, column 19): unexpected keyword `From`, expected identifier."

**To Reproduce**
1. Try to run the query `select RequestDto.From from stream where Route like '/email%' ci and Elapsed > 1000 limit 1`

**Expected behavior**
The query should execute, as From is not a keyword in this context. I had to run it this way instead `select RequestDto['From'], RequestDto['To'] from stream where Route like '/email%' ci and Elapsed > 1000 limit 1`

**Screenshots**
![image](https://github.com/user-attachments/assets/f2e678ee-727b-4f01-b60f-7fe833fc2a46)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Seq Version 2024.3.12250
 - Using Docker? No

**Comment by nblumhardt** [comment] 2024-10-17 20:49
Thanks for the note 👍 

This is by design; the `RequestDto['From']` syntax is correct, though it's an annoying limitation that we intend to lift when there's an opportunity (likely by tokenizing any keyword immediately following `.` as if it's an identifier).

**Comment by nblumhardt** [comment] 2024-10-24 01:56
We've committed this change to 2025.1.

**Closed by nblumhardt** 2024-10-24 01:56 UTC
Labels: enhancement
