### ISSUE TITLE
"Order by" not supported when grouping by Time

### ISSUE THREAD

**Issue by laurencee** [datalust/seq-tickets#547] opened 2017-04-10 01:16 UTC
Seq version 3.4.20

**Bug**
The following query does not apply the order by statement:

```
select count(*) as Occurrences
from stream
group by Time(1m)
order by Occurrences desc
limit 1000
```

**Comment by nblumhardt** [comment] 2017-04-10 21:50
Hi Laurence, thanks for the note.

The behavior here is a little confusing, but is essentially by design. Seq treats the `time()` dimension specially - it generates a timeseries result (the response from the server is not a flat table). The ordering will be applied to rowsets within the timeseries - but each rowset only has a single value in this case, so there's no visible impact.

I need to think further through ways in which one might express this.

**Comment by laurencee** [comment] 2017-04-12 07:27
Hmm I can see the logic there but it also seems valid that someone (such as myself) would want to see what periods of time had the highest occurrence rate of whatever is being filtered.

**Comment by nblumhardt** [comment] 2017-04-12 10:09
Yes, I agree 👍

**Comment by BlairPaine** [comment] 2017-07-06 14:16
This also appears to be a problem for Dashboards (4.0.60).

It forced a 6 hour time slice but I would like it sliced into 24 hour periods over 30 days. The group by gets automatically added and I cannot edit it. Not sure if this should be part of this issue, a new issue, or #565?

**Comment by nblumhardt** [comment] 2017-07-06 22:58
Hi @BlairPaine! Thanks for dropping by :-)

I think https://github.com/datalust/seq-releases/issues/581 already implements what you're looking for here - correct?

**Comment by BlairPaine** [comment] 2017-07-07 08:51
Hi @nblumhardt. Yes correct. I missed that enhancement.  Great work - I'm looking forward to it.

**Comment by nblumhardt** [comment] 2019-04-23 03:10
We're still considering the different ways we can approach this (really, some things take time :-) ) - but won't make a change in the near future so we'll close this ticket. Thanks @laurencee !

**Closed by nblumhardt** 2019-04-23 03:10 UTC
Labels: enhancement
