### ISSUE TITLE
After a Microsoft Authentication, redirect to the original linked page

### ISSUE THREAD

**Issue by janpieterz** [datalust/seq-tickets#1125] opened 2021-02-07 09:47 UTC
If you click on a Seq link but your authentication has expired (happens daily with our MS authentication), completing the authentication means you get redirected to the main Seq page rather than the link you clicked on.

**Comment by nblumhardt** [comment] 2021-02-07 21:54
Hi @janpieterz! Thanks for raising this. It's a duplicate of #1041 - but just regarding your frequent logouts, are you running a 2020.3 or later build? We switched from ADAL to OIDC as the backbone of AAD auth in #1023, which may have an effect on this.

**Comment by janpieterz** [comment] 2021-02-08 08:29
Hi @nblumhardt :) 
Running 2020.5 on both instances where this happens. Happy to expose some logs to you or do some tracking of something in case you have any suggestions?

**Comment by nblumhardt** [comment] 2021-02-09 05:35
Thanks for the reply! We can definitely dig in and see if there are any clues in Seq's diagnostic report 👍  - I'll keep any eye out for email from you.

I'll close this, and if we spot something we can improve in Seq itself, we can raise a new ticket. Thanks!

**Closed by nblumhardt** 2021-02-09 05:35 UTC
Labels: duplicate

**Comment by nblumhardt** [comment] 2021-03-09 06:11
Hi @janpieterz - just letting you know this is still on the radar. I have one possible mitigation to explore that I'm hoping to get into 2021.2 behind a feature flag, will keep you posted.

**Comment by janpieterz** [comment] 2021-03-14 08:59
Super, thanks.

**Comment by nblumhardt** [comment] 2021-03-22 07:32
@janpieterz do you see any improvement after upgrading to 2021.2.5495 and enabling the flag below?

```
seq config -k features.enabled -v oidcsavetokens
seq service restart
```

**Comment by janpieterz** [comment] 2021-03-27 09:15
Hi @nblumhardt I've just installed it on the 2 instances I manage and set the config value. I'll report back (but feel free to poke me in case I forget 😉 )

**Comment by nblumhardt** [comment] 2021-04-15 05:13
Howdy @janpieterz - any improvement? :-)

**Comment by janpieterz** [comment] 2021-04-16 23:18
Seems to still happen quite regularly. Difficult to "trace" how often / what duration of course.
Crazy idea, would it be helpful if I expose a login to you with basically no viewing permissions?

**Comment by nblumhardt** [comment] 2021-04-18 23:22
Thanks @janpieterz - we're going to switch some of our own services to use it and see whether we can repro here, but I'll let you know if we still need to dig deeper after that 👍
