### ISSUE TITLE
Support OpenTelemetry?

### ISSUE THREAD

**Issue by CrispyDrone** [datalust/seq-tickets#1011] opened 2020-08-12 20:21 UTC
To give some introduction, the company I work for has a major issue with lack of visibility on the runtime behavior of all the applications. 

After a long, hard struggle, I was unable to convince everyone of Seq. The company ultimately decided to go with Azure Monitor for various reasons ranging from a desire to move everything to the cloud, but also because of a few critical features that Azure Monitor offers out of the box over Seq.

These 2 features are:

1. [Application map](https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-map?tabs=net), which can show runtime dependencies between applications and other infrastructure such as databases and external services.
2. Tracing allowing dependency and performance visualizations see for example https://docs.microsoft.com/en-us/azure/azure-monitor/app/transaction-diagnostics

Both features are possible through distributed tracing. The [OpenTelemetry specification](https://opentelemetry.io/) describes the requirements and expectations of implementations of open telemetry. 

Seq could act as one of the backend services ingesting this open telemetry data, and support similar visualizations as Application Insights does.

I've only just started reading the specification, and I obviously don't know seq's internals. My questions are the following:

1. Is there any interest from the Seq team in supporting OpenTelemetry?
2. What would it take for Seq to be able to ingest such telemetry data? Can it already do that today?
3. Could Seq natively support distributed trace visualizations (Just want to mention this issue https://github.com/datalust/seq-tickets/issues/844), application maps,..
4. Would it be possible to extend the capabilities of Seq apps to be able to display "arbitrary things" in the UI?

Looking forward to your answer!

**Comment by nblumhardt** [comment] 2020-08-13 05:16
Hi @CrispyDrone - thanks for taking the time to write such a thoughtful and detailed post.

As you've noticed, #844 is standing in as the tracking issue for this, currently, though it's lacking the requisite mention of OpenTelemetry, which stands a good chance of being the foundation for all of this work.

I'll answer your four questions, but close this as a duplicate of the other issue, and make some notes over there to call attention to OpenTelemetry specifically. It would be great to continue discussion over on that ticket, since it will keep all of the notes in one place :-)

1. We're very interested in this; we have a feature backlog that prioritizes some other highly-requested things ahead (namely HA/clustering support), so it's some way off in the future, but still high on our list to consider
2. Seq can accept span and trace identifiers in logs, but has no native visualization functionality for putting these things together in a hierarchy/call graph/etc.
3. I think this and point 1) above are largely the same requirement, as we'd be best off leaning on existing instrumentation/standards for recording and identifying traces
4. Probably not, in the foreseeable future, though UI extensibility is not completely off our radar :-)

Sorry if this reply is a little rushed, it's a deep and complex area. Thanks again for the input, hopefully the next time you pitch Seq we'll have moved this forward a little :-)

**Closed by nblumhardt** 2020-08-13 05:16 UTC
Labels: enhancement

**Comment by nblumhardt** [comment] 2023-05-18 22:49
Just a quick note to point out https://github.com/datalust/seq-tickets/issues/1679, which is the first step in us moving this forward.
