### ISSUE TITLE
Integrated authentication link is hidden for non-IE browsers

### ISSUE THREAD

**Issue by brianary** [datalust/seq-tickets#840] opened 2019-04-11 16:30 UTC
When using Chrome or Firefox with newer versions of Seq, there's no UI to log in to Seq with integrated authentication. It's being hidden for non-IE browsers. Going to http://seq-server-name/integrated works fine, but is less convenient/discoverable.

**Comment by nblumhardt** [comment] 2019-04-11 21:11
Hi Brian! Thanks for the heads-up. This is a duplicate of #766 - we've just reverted and shipped this change in 5.1 :+1:

**Closed by nblumhardt** 2019-04-11 21:11 UTC
Labels: duplicate
