### ISSUE TITLE
When upgrading Seq, the installer should detect (and use) current installation path

### ISSUE THREAD

**Issue by caioproiete** [datalust/seq-tickets#692] opened 2018-05-24 19:30 UTC
I have Seq installed on a different path than the suggested one by the installer, and every time I upgrade Seq to a new version, **I have to remember that**, and change it in the installer.

Current installed version:
![image](https://user-images.githubusercontent.com/177608/40509282-94eb8e56-5f6f-11e8-8b0e-e2ee3d41ac44.png)

Installer upgrading to version 4.2.113:
![image](https://user-images.githubusercontent.com/177608/40509364-aced2da2-5f6f-11e8-9dc5-1fcbd9ad5d42.png)

**Comment by nblumhardt** [comment] 2018-05-25 02:05
Thanks for the report, Caio - we'll take a look.

**Comment by nblumhardt** [comment] 2019-03-18 04:09
I've spent some time looking into this and I'm afraid any fix runs the risk of causing problems we might not detect before 5.1 goes out (my WiX-fu is not strong, today).. Pushing it back to the backlog, sorry folks.

**Comment by nblumhardt** [comment] 2019-04-23 03:54
Thinking about this again, the issue is significantly mitigated by us implementing #693, and the user experience there would be much better. We'll close this and focus our efforts on auto-updates.

**Closed by nblumhardt** 2019-04-23 03:54 UTC
Labels: bug
