### ISSUE TITLE
Exception when binding volume

### ISSUE THREAD

**Issue by amaechler** [datalust/seq-tickets#701] opened 2018-07-13 22:07 UTC
I'm running a Windows 2016 Server (10.0.17134) docker ee host, running the latest seq linux container (https://hub.docker.com/r/datalust/seq/). Whenever I try to use any persistent storage, I am running into what I'm assuming to be permission issues.

This might be related to linux container support still being WIP (as highlighted [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers)).

Running a seq server instance with ephemeral storage works as expected.

(example with a docker volume, also tried bind mounts)
```
$ docker run -e ACCEPT_EULA=Y -v seq-data:/data -p 80:80 -p 5341:5341 datalust/seq:latest

...
docker : [21:34:52 INF] Seq 5.0.949-pre running on OS Linux 4.12.14-linuxkit #1 SMP Mon Sep 25 12:27:00 UTC 2017
[...]
1:34:54 INF] Opening document store /data/Documents/default.quince
[21:34:54 ERR] Uncaught exception from worker Start background processes (75498be7-4d1f-4fbc-a91e-ab3a7c498f01)
[...]
Failed to open environment at path /data/Documents/default.quince (See inner exception for details.) 
LightningDB.LightningException: Failed to open environment at path /data/Documents/default.quince --->
LightningDB.LightningException: Operation not supported
   at LightningDB.Native.Lmdb.check(Int32 statusCode)
   at LightningDB.LightningEnvironment.Open(EnvironmentOpenFlags openFlags, UnixAccessMode accessMode)
   --- End of inner exception stack trace ---
   at LightningDB.LightningEnvironment.Open(EnvironmentOpenFlags openFlags, UnixAccessMode accessMode)
   at Quince.Storage.Lmdb.LmdbDocumentStore..ctor(String path)
   at Seq.Server.SeqServerModule.InitStorageSubsystem(IComponentContext c)
[... (lots of Autofac resolving)]
   at Seq.Server.ServiceProcess.ServerService.<Start>b__12_0(CancellationToken cancel)
   at Flare.Workers.WorkerPool.<>c__DisplayClass4_0.<Run>b__0()
```

<details>
<summary>Docker Version</summary>

```
Client:
 Version:      17.10.0-ee-preview-3
 API version:  1.33
 Go version:   go1.8.4
 Git commit:   1649af8
 Built:        Fri Oct  6 17:52:28 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.10.0-ee-preview-3
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.4
 Git commit:   b8571fd
 Built:        Fri Oct  6 18:01:48 2017
 OS/Arch:      windows/amd64
 Experimental: true
```
</details>

**Comment by nblumhardt** [comment] 2018-07-13 23:06
Interesting - thanks for the report, @amaechler. We'll see if we can reproduce this - we did hit some problems using LMDB on WSL, as well, so (assuming similar underlying tech?) these could be related. Will keep you posted!

**Comment by nblumhardt** [comment] 2018-07-13 23:08
(Ah, I see via the link that this is using Hyper-V, so probably unrelated.)

**Comment by nblumhardt** [comment] 2018-07-25 04:41
Hi @amaechler - we've reviewed the linked documentation regarding unsupported filesystem operations, and think this will be the cause here. We'll close this for now, but once Linux container support for Server 2016/EE is baked, we're keen to re-test.

Best regards,
Nick

**Closed by nblumhardt** 2018-07-25 04:41 UTC
Labels: bug, platform-docker, pre-only
