### ISSUE TITLE
Log error in android

### ISSUE THREAD

**Issue by mss-parveensachdeva** [datalust/seq-tickets#650] opened 2018-01-12 12:20 UTC
Using xamarin forms pcl is logging any error Seq Server. On inspecting the log i found that its in queue but not logging it. Please help me to sort out it.

**Comment by nblumhardt** [comment] 2018-01-12 20:22
Hello,

The first thing to try is to work through the troubleshooting steps here: https://github.com/serilog/serilog-sinks-seq#troubleshooting

If you don't find the cause that way, can you please reply with what you see/find at each step?

Best regards,
Nick

**Comment by nblumhardt** [comment] 2018-01-15 04:56
Hi @mss-parveensachdeva  - any luck with the troubleshooting?

Best regards,
Nick

**Comment by mss-parveensachdeva** [comment] 2018-01-15 06:04
I am using Seq.Client.Portable and in this library i can not find any troubleshooting on android app in xamarin forms.

**Comment by nblumhardt** [comment] 2018-01-15 06:29
Thanks for the reply. _Seq.Client.Portable_ plugs into Serilog, so the troubleshooting steps will be similar - ingestion log, `SelfLog`, though the package depends on a very old Serilog so you may need to update that first.

You should have much better results using https://www.nuget.org/packages/serilog.sinks.seq, which should run fine under Xamarin; ideally, upgrade to Serilog 2.6 and Serilog.Sinks.Seq version 4.0.0, and remove Seq.Client.Portable for the best experience. If you see any errors upgrading, please let me know.

Seq.Client.Portable is very old, unmaintained code - it's been replaced by Serilog.Sinks.Seq which covers similar targets via the .NET Standard platform targets.

Let me know how you go!

Best regards,
Nick

**Comment by nblumhardt** [comment] 2018-02-02 04:18
Closing due to the age of this ticket, please let us know if you still have trouble using the newer client versions. Thanks!

**Closed by nblumhardt** 2018-02-02 04:18 UTC
