### ISSUE TITLE
Quality of Life: Sorting Columns

### ISSUE THREAD

**Issue by BBSDeadEye** [datalust/seq-tickets#2289] opened 2024-10-07 09:45 UTC
Currently you are not able to sort columns, once they are added to a signal, you have to create the signal again, without columns, and add them manually.

![image](https://github.com/user-attachments/assets/3b01c0e5-342b-4a9a-b2ca-24e964d5503d)

So I think it would be nice to either dragdrop them or have some kind of sorting mode you can switch to.

**Comment by liammclennan** [comment] 2024-10-07 09:49
Thanks @BBSDeadEye 
I can see how this would be nice.

**Comment by KodrAus** [comment] 2024-10-09 04:56
Duplicate of #2055; let's track this one in the other ticket :+1:

**Closed by KodrAus** 2024-10-09 04:56 UTC
Labels: enhancement
