### ISSUE TITLE
System.NullReferenceException when receiving logs from Grafana Alloy

### ISSUE THREAD

**Issue by JotaCe14** [datalust/seq-tickets#2331] opened 2024-12-03 14:20 UTC
**Describe the bug**
I'm using Grafana Alloy to send OTLP logs to Seq using the /ingest/otlp/v1/logs but i get the following error:

HTTP POST /ingest/otlp/v1/logs responded 500 in 1.3669 ms
System.NullReferenceException: Object reference not set to an instance of an object.
   at Serilog.Rendering.MessageTemplateRenderer.RenderPropertyToken(PropertyToken pt, IReadOnlyDictionary`2 properties, TextWriter output, IFormatProvider formatProvider, Boolean isLiteral, Boolean isJson)
   at Serilog.Events.MessageTemplate.Render(IReadOnlyDictionary`2 properties, TextWriter output, IFormatProvider formatProvider)
   at Serilog.Events.MessageTemplate.Render(IReadOnlyDictionary`2 properties, IFormatProvider formatProvider)
   at Seq.Server.Features.OpenTelemetry.OpenTelemetryMappingHelpers.HeuristicGetMessage(String maybeTemplate, Dictionary`2 properties, Dictionary`2 renderingsByProperty)
   at Seq.Server.Features.OpenTelemetry.OpenTelemetryLogRecordMapping.ReadFromServiceRequest(ExportLogsServiceRequest request, Int64 rawEventMaximumContentLength, ITimestampPolicy timestampPolicy, IReadOnlyList`1 appliedProperties, FlatEvent[]& events, String& errorMessage)
   at Seq.Server.Web.Api.IngestionController.TryParseOtlpProtoBody[TRequest](Input input, FlatEvent[]& events, String& errorMessage)
   at Seq.Server.Web.Api.IngestionController.DoIngest(BodyParser parseBody, ResponseFormatter formatResponse)
   at Seq.Server.Web.Api.IngestionController.IngestOtlpLogsV1()
   at lambda_method1203(Closure, Object, Object[])

**To Reproduce**
1. Install grafana alloy
2. Send OTLP to grafana alloy from applications
3. Configure grafana alloy to send logs to Seq Instance
4. See error from the logs

**Expected behavior**
I would like to ingest the logs.

**Screenshots**
![image](https://github.com/user-attachments/assets/4eb2b286-7bc3-4d8c-a64b-438e8a6335f8)
![image](https://github.com/user-attachments/assets/a892eb67-13fc-44b0-8680-bf32e5b5cc91)

**Environment (please complete the following information):**
 - OS: Linux
 - Seq Version 2024.3.12680
 - Using Docker? Yes
 - Using Kubernetes? Yes

**Additional context**
In Loki I can see the following properties:

attributes_ApplicationName | Payouts.Api.Worker.Consumer
  | attributes_Elapsed | 801.6333
  | attributes_IntegrationEventId | b2084fb9-b565-4329-a3f9-4079b924c9a8
  | attributes_MachineName | payouts-api-worker-consumer-deployment-786b946658-rhdkx
  | attributes_OperationId | e87ee4c2-3790-47a1-97b2-0ca371ad75b2
  | attributes_Outcome | completed
  | attributes_PartnerId | 1
  | attributes_PaymentId | 5499103
  | attributes_ThreadId | 38
  | body | Executing transaction {Outcome} in {Elapsed:0.0} ms
  | cluster | rpp-pd-k8s-stg
  | detected_level | DEBUG
  | exporter | OTLP
  | instance | payouts.payouts-api-worker-consumer-deployment-786b946658-rhdkx.payouts-api-worker-consumer-container
  | instrumentation_scope_name | None
  | job | payouts/payouts-api-worker-consumer-deployment
  | level | DEBUG
  | namespace | payouts
  | pod | payouts-api-worker-consumer-deployment-786b946658-rhdkx
  | resources_host_name | grafana-k8s-monitoring-alloy-0
  | resources_k8s_cluster_name | rpp-pd-k8s-stg
  | resources_k8s_container_name | payouts-api-worker-consumer-container
  | resources_k8s_deployment_name | payouts-api-worker-consumer-deployment
  | resources_k8s_namespace_name | payouts
  | resources_k8s_node_name | aks-system-34565020-vmss00000a
  | resources_k8s_pod_ip | 10.10.128.155
  | resources_k8s_pod_name | payouts-api-worker-consumer-deployment-786b946658-rhdkx
  | resources_k8s_pod_start_time | 2024-12-02T22:26:38Z
  | resources_k8s_pod_uid | c17f3b3c-1f09-460a-b090-5092403d36d2
  | resources_k8s_replicaset_name | payouts-api-worker-consumer-deployment-786b946658
  | resources_os_type | linux
  | resources_service_instance_id | payouts.payouts-api-worker-consumer-deployment-786b946658-rhdkx.payouts-api-worker-consumer-container
  | resources_service_name | payouts-api-worker-consumer-deployment
  | resources_service_namespace | payouts
  | resources_service_version | 2e785e7
  | resources_telemetry_sdk_language | dotnet
  | resources_telemetry_sdk_name | opentelemetry
  | resources_telemetry_sdk_version | 1.9.0
  | service_name | payouts/payouts-api-worker-consumer-deployment
  | severity | Debug
  | spanid | 10b4c4433de6b22f
  | traceid | c686c2da1de3a0c2103c9eca96253695

**Comment by nblumhardt** [comment] 2024-12-03 21:07
Thanks for the report. This seems to be a variant of #2314, which we hadn't otherwise encountered in the wild. We have a fix committed internally; we'll push ahead and aim to publish a patch within 24 hours or so.

**Comment by nblumhardt** [comment] 2024-12-04 06:37
Closing this one as a duplicate of #2341. The patch build `2024.3.13080` should be published first thing tomorrow morning AEST. Thanks again for reporting this!

**Closed by nblumhardt** 2024-12-04 06:37 UTC
Labels: duplicate

**Comment by nblumhardt** [comment] 2024-12-05 00:33
The patch has been published now; if you run into any further issues after updating, please let me know. Cheers!
