### ISSUE TITLE
Event Cache not populating

### ISSUE THREAD

**Issue by mason-mcglothlin** [datalust/seq-tickets#653] opened 2018-01-19 20:46 UTC
We upgraded from Seq 4.1 to 4.2 several days ago. Today we noticed that the RAM event cache isn't populating.

![image](https://user-images.githubusercontent.com/8096989/35170484-0e88bb1e-fd26-11e7-9124-9cf94427f499.png)

Normally when Seq starts up we would see a message that it's warming up. But we don't see that. It just seems to always go to the HDD to retrieve events. In the Seq logs there's these entries:

    {
        "@t":"2018-01-19T20:15:05.0348861Z",
        "@mt":"Initial memory cache warm-up {Outcome} in {Elapsed:0.0} ms",
        "@r":["2.7"],
        "Outcome":"completed",
        "Elapsed":2.6642,
        "OperationId":"e297f24f-3058-4b7b-a8b5-5461bfe77b39"
    }

    {
        "@t":"2018-01-19T20:15:05.0504690Z",
        "@mt":"{WarmSegments} segments warmed up ({@Shared})",
        "WarmSegments":0,
        "Shared":{"Schemata":0,"Strings":0},
        "SourceContext":"Flare.Events.Cache.SegmentCache"
    }

Restarting Seq server didn't fix the problem.

The server has 16GB of RAM. Task Manager is showing that Seq is using 226MB of RAM. All the other applications on the server combined are using well under 1GB of RAM. Task Manager is showing that 96% of the memory is in use, with Seq Server being the top consumer.

![image](https://user-images.githubusercontent.com/8096989/35170888-55ec2b84-fd27-11e7-9af5-43bddae50799.png)

![image](https://user-images.githubusercontent.com/8096989/35170902-63b8c254-fd27-11e7-9aa6-08fc43c79f11.png)

**Comment by mason-mcglothlin** [comment] 2018-01-19 21:20
Rebooted the server VM and it started loading data in RAM. I don't believe we rebooted after upgrading from 4.1 to 4.2, so perhaps there's a bug in the upgrade process that keeps it from caching until the server is rebooted?

The issue is resolved for me, but I'm happy to assist with any post-mortem analysis you might need in case it will help others.

**Comment by andymac4182** [comment] 2018-01-19 23:08
@mason-mcglothlin Is there a chance you are using LMDB data storage?

**Comment by nblumhardt** [comment] 2018-01-21 22:32
Thanks for the report and follow-up @mason-mcglothlin - it would be great to do a bit of post-mortem on this. As @andymac4182 suggested, we've seen some similar things in the use of LMDB storage (it's an opt-in), so that would be interesting to know.

If you can send the full diagnostic report from the server to our support@getseq.net address, we should be able to track down the cause there. The report is in _Settings_ > _Diagnostics_ (bottom of page) in Seq itself.

Best regards,
Nick

**Comment by mason-mcglothlin** [comment] 2018-01-23 16:11
We did not opt-in to LMDB storage. I have now sent the full diagnostic report in to the mentioned email address.

**Comment by nblumhardt** [comment] 2018-01-23 22:22
Thanks again for the diagnostic info, I am fairly sure this is due to a data corruption that will be repaired via the `seq compact --repair` steps I sent. Closing for now, will re-open if we identify other issues.

**Closed by nblumhardt** 2018-01-23 22:22 UTC
