### ISSUE TITLE
Events logged via sqelf with level `@l` specified as level appear as raw JSON

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-tickets#843] opened 2019-04-19 10:02 UTC
Hi,

Related to #805, I'm playing around with docker log forwarding from a node web app using the `pino` logging library. Not sure if I should open the issue in https://github.com/datalust/sqelf ...

What I do is that I take the output from pino, which is *newline-delimited* JSON, and transform it a bit to add some fields of the [`CLEF`](https://github.com/serilog/serilog-formatting-compact) log format. 

This seems to work fine when generating JSON events that have a `@mt` field : 

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/160544/56419247-dedc2b00-6299-11e9-9fb2-fcc9472a2082.png">

... but for some reason, when error occurs and I'm logging them at the error level with an attached exception, they show up in Seq as "raw" json, with the level ignored, and no exception attached. 

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/160544/56419345-311d4c00-629a-11e9-95e1-b59bd394e9e5.png">

The JSON seems like legit `clef` to me, but I may be missing something. Here is the "raw json" exported from Seq (a bit unreadable because it is doubly-encoded json) : 

```json
{
    "@t": "2019-04-19T09:40:47.5690000Z",
    "@mt": "{{\"level\":60,\"time\":1555666847568,\"pid\":26,\"hostname\":\"7699af7aee57\",\"name\":\"public\",\"err\":{{\"type\":\"Error\",\"message\":\"connect ECONNREFUSED 192.168.16.4:27017\",\"stack\":\"Error: connect ECONNREFUSED 192.168.16.4:27017\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)\",\"errno\":\"ECONNREFUSED\",\"code\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"192.168.16.4\",\"port\":27017}},\"msg\":\"Initialization failed\",\"v\":1,\"@t\":\"2019-04-19T09:40:47.568Z\",\"@mt\":\"Initialization failed\",\"@l\":5,\"@x\":\"Error: connect ECONNREFUSED 192.168.16.4:27017\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)\"}}",
    "@m": "{\"level\":60,\"time\":1555666847568,\"pid\":26,\"hostname\":\"7699af7aee57\",\"name\":\"public\",\"err\":{\"type\":\"Error\",\"message\":\"connect ECONNREFUSED 192.168.16.4:27017\",\"stack\":\"Error: connect ECONNREFUSED 192.168.16.4:27017\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)\",\"errno\":\"ECONNREFUSED\",\"code\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"192.168.16.4\",\"port\":27017},\"msg\":\"Initialization failed\",\"v\":1,\"@t\":\"2019-04-19T09:40:47.568Z\",\"@mt\":\"Initialization failed\",\"@l\":5,\"@x\":\"Error: connect ECONNREFUSED 192.168.16.4:27017\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)\"}",
    "@i": "a5573d90",
    "host": "linuxkit-025000000001",
    "created": "2019-04-19T09:40:42.3856343Z",
    "image_name": "tibo-XXXXXXX-log:latest",
    "image_id": "sha256:cf3420c9121a232731edd1b0d925d403bde45e2bbacbe12f565f629dd4007962",
    "command": "/bin/sh -c ( node dist/start-db-deploy.js | node dist/pino-clef.js ) && ( node dist/start.js  | node dist/pino-clef.js)",
    "container_id": "7699af7aee577f9125298f85c696d82b710f077d7ef840f9679332605511c07b",
    "container_name": "XXXXXXX_XXXXXXX-service-public_1",
    "tag": "7699af7aee57"
}
``` 

Here are a few assumptions I took for the conversion from pino to CLEF : 

- level mapping follows those rules : 
```ts
const levels: any = {
  60: 5, // FATAL
  50: 4, // ERROR
  40: 3, // WARN
  // 30: 2, // INFO = default when not provided
  20: 1, // DEBUG
  10: 0, // TRACE / Verbose
};
```

i.e. I pass `@l` providing number values from `0` to `5` to represent `Verbose` to `Fatal`. (but omit it when `Information`)

- `@x` should be a string when attaching error details

Am I doing something obviously wrong ?

**Comment by nblumhardt** [comment] 2019-04-20 22:03
Interesting - thanks for the report @tsimbalar. Sounds like we could have a `sqelf` issue around handling of `@x`, but it seems pretty straightforward:

 * https://github.com/datalust/sqelf/blob/dev/sqelf/src/process/clef.rs#L39
 * https://github.com/datalust/sqelf/blob/dev/sqelf/src/process/mod.rs#L138

The nested JSON is valid, and `@x` looks fine:

![image](https://user-images.githubusercontent.com/342712/56462745-ca1fa480-640b-11e9-9539-def1c996829b.png)

Will test properly this week and let you know what we find 👍

**Comment by tsimbalar** [comment] 2019-04-22 20:03
Ok, I've taken another look .... it looks like this is not related to the exception, but more to the level ... ...

Those events also show up as "raw" JSON : 

```json
{
   "level":30,
   "time":1555963289329,
   "pid":25,
   "hostname":"4f4d1ffcf844",
   "name":"public",
   "msg":"Public API running on 0.0.0.0:8101",
   "v":1,
   "@t":"2019-04-22T20:01:29.329Z",
   "@mt":"Public API running on 0.0.0.0:8101",
   "@l":5
}
```

I get this behavior as soon as I provide `@l` (as a number) myself for the level ...

**Comment by tsimbalar** [comment] 2019-04-22 20:11
Ok, so : 

```json
{
   "level":30,
   "time":1555963289329,
   "pid":25,
   "hostname":"4f4d1ffcf844",
   "name":"public",
   "msg":"Public API running on 0.0.0.0:8101",
   "v":1,
   "@t":"2019-04-22T20:01:29.329Z",
   "@mt":"Public API running on 0.0.0.0:8101",
   "@l":"FATAL"
}
```

properly shows up as *Fatal* in Seq .... and it seems that the level indicator that shows up in *Seq* actually has the same case as the level I provided ... Is this by design ? 

The README in https://github.com/serilog/serilog-formatting-compact#reified-properties says about the level : 

> `@l` | Level | An implementation-specific level identifier (string or number)

so I had understood that passing the underlying `int` of the `LogLevel` `enum` would do it, but maybe that was a misunderstanding on my side ?

**Comment by nblumhardt** [comment] 2019-04-23 00:59
😂 I just recently rewrote the filter into that form - it's getting tricky to catch all the possible level names...

Thanks for the follow-up on this. It's a bit of a trap - the CLEF format is tolerant of numeric levels, but Seq won't accept them. I think we have to close this as "by design" for now, but thanks for getting it on the radar 👍

**Closed by nblumhardt** 2019-04-23 00:59 UTC
